### Escrapear los precios de USD y EUR
POST http://0.0.0.0:8080/api/v1/exchange-rates/scrape
Content-Type: application/json

### Precios de dolar en COP 
GET https://www.datos.gov.co/api/v3/views/32sa-8pi3/query.json?query=SELECT%20valor%20order%20by%20vigenciadesde%20desc%20limit%201
Content-Type: application/json

### Buscar últimos precios
GET http://0.0.0.0:8080/api/v1/exchange-rates/latest
Content-Type: application/json

### Buscar últimos precios de 1 par
GET http://0.0.0.0:8080/api/v1/exchange-rates/USDVES/latest
Content-Type: application/json


### Buscar histórico de precios de 1 par
GET http://0.0.0.0:8080/api/v1/exchange-rates/USDVES/history?limit=30
Content-Type: application/json

### EURCOP banrep
POST https://suameca.banrep.gov.co/indicadores-economicos-del-dia-back/rest/indicadoresEconomicosDiaService/consultarIndicador
Content-Type: application/json

{
    "idIndicador": 1321,
    "datosIndicador": {"tipo": "Media"}
}

### EURUSD banrep
POST https://suameca.banrep.gov.co/indicadores-economicos-del-dia-back/rest/indicadoresEconomicosDiaService/consultarIndicador
Content-Type: application/json

{
    "idIndicador": 1311,
    "datosIndicador": {}
}

### USDT Binance
POST https://p2p.binance.com/bapi/c2c/v2/friendly/c2c/adv/search
Content-Type: application/json

{
    "fiat": "VES",
    "page": 1,
    "rows": 1,
    "tradeType": "SELL",
    "asset": "USDT",
    "countries": [],
    "proMerchantAds": false,
    "shieldMerchantAds": false,
    "filterType": "tradable",
    "periods": [],
    "additionalKycVerifyFilter": 0,
    "publisherType": "merchant",
    "payTypes": [],
    "classifies": [
        "mass",
        "profession",
        "fiat_trade"
    ],
    "tradedWith": false,
    "followed": false,
    "privilegeDesc": null
}

### USDTCOP
GET https://www.binance.com/bapi/asset/v2/public/asset-service/product/get-product-by-symbol?symbol=USDTCOP
